import logging

logger = logging.getLogger(__name__)

import json
import os
import re
import time
from datetime import datetime
from google.cloud import datastore
import uuid
import traceback
import concurrent.futures
from googleapiclient.discovery import build

from services import ai_engine, workspace_client, slides_engine
import rule_engine

def load_personas_from_json():
    if os.path.exists('personas.json'):
        with open('personas.json', 'r') as f:
            return json.load(f).get('executives', [])
    return []

def run_sequential_debate_personas(active_personas, virtual_deck, deal_desc, research_context, workspace_context, job_id=None):
    critiques_list = []
    debate_transcript = ""
    for p in active_personas:
        if job_id:
            append_event(job_id, {"type": "log", "message": f"[INFO] Agent {p.get('name')} analyzing context and previous critiques..."})
            
        res = ai_engine.run_persona_node(p, virtual_deck, deal_desc, research_context, workspace_context, debate_transcript)
        if res:
            critiques_list.append(res)
            debate_transcript += f"\n{res}\n"
            
    return "\n".join(critiques_list)


GCP_PROJECT = os.environ.get('GOOGLE_CLOUD_PROJECT', 'internal-xr-ai-tools-977945')
datastore_client = datastore.Client(project=GCP_PROJECT)

def append_event(job_id, event):
    """Utility to append an event to the Datastore job document."""
    try:
        event['timestamp'] = datetime.utcnow().isoformat()
        job_key = datastore_client.key('SimulationJob', job_id)
        
        event_key = datastore_client.key('SimulationEvent', parent=job_key)
        excludes = [k for k, v in event.items() if isinstance(v, str) and len(v.encode('utf-8', errors='ignore')) > 1400]
        event_entity = datastore.Entity(key=event_key, exclude_from_indexes=excludes)
        event_entity.update(event)
        
        datastore_client.put(event_entity)
        
        job = datastore_client.get(job_key)
        if job:
            job['updated_at'] = datetime.utcnow()
            datastore_client.put(job)
            
    except Exception as e:
        logger.info(f"Failed to append event to Datastore for job {job_id}: {e}")

def execute_simulation_job(job_id, creds, source_presentation_id, deal_desc, org_filter, method, deal_size_str, risk_flags):
    def get_moma_browser_url(p):
        pid = p.get('id', 'default')
        for ext in ['.png', '.jpg', '.jpeg']:
            if os.path.exists(os.path.join(os.getcwd(), 'static', 'avatars', f"{pid}{ext}")):
                return f"/avatars/{pid}{ext}"
        
        ldap = p.get('ldap')
        email = f"{ldap}@google.com" if ldap else f"{pid}@google.com"
        return f"https://moma-teams-photos.corp.google.com/photos/{email}?sz=192"
        
    def get_signed_avatar_url(p):
        pid = p.get('id', 'default')
        
        from google.cloud import storage
        from datetime import timedelta
        # Attempt to synthesize a completely secure 15-minute Signed URL natively.
        try:
            storage_client = storage.Client()
            bucket_name = os.environ.get('GOOGLE_CLOUD_PROJECT', 'internal-xr-ai-tools-977945') + '-sync-assets'
            bucket = storage_client.bucket(bucket_name)
            blob = bucket.blob(f"moma_images/{pid}.png")
            if blob.exists():
                return blob.generate_signed_url(version="v4", expiration=timedelta(minutes=15), method="GET")
        except Exception as e:
            logger.warning(f"Failed to sign GCS URL for {pid}. Service Account may lack Token Creator IAM. Falling back to avatar omission: {e}")
        
        # Fallback to None (omits image from payload entirely) if the IAM signing scopes fail.
        return None

    try:
        append_event(job_id, {"type": "step", "index": 0, "title": "Vision Digest & Mapping", "progress": 5})
        append_event(job_id, {"type": "log", "message": "[INFO] Initializing Mapping Engine"})
        
        service_slides = slides_engine.get_slides_client(creds)
        service_drive = slides_engine.get_drive_client(creds)
        
        append_event(job_id, {"type": "log", "message": "[INFO] Cloning Target Presentation"})
        
        try:
            copied_file = slides_engine.copy_presentation(service_drive, source_presentation_id, 'Hardened Deal Package (PEX BC V3) - Autogenerated')
            presentation_id = copied_file.get('id')
        except Exception as e:
            append_event(job_id, {"type": "log", "message": f"[CRITICAL] Failed to copy presentation: {e}"})
            raise e
        
        append_event(job_id, {"type": "log", "message": "[INFO] Reading Slide Elements"})
        append_event(job_id, {"type": "log", "message": f"[INFO] Analyzing geometric coordinate mapping for {source_presentation_id}..."})
        slides_data = slides_engine.extract_presentation_data(service_slides, presentation_id)
        append_event(job_id, {"type": "log", "message": f"[SUCCESS] Extracted {len(slides_data)} slides"})
        
        append_event(job_id, {"type": "step", "index": 1, "title": "Track Determination", "progress": 10})
        append_event(job_id, {"type": "log", "message": "[INFO] Identifying Review Track based on metrics"})
        
        active_personas = rule_engine.get_required_personas(deal_desc, org_filter, deal_size_str, risk_flags)
        if not active_personas: 
            append_event(job_id, {"type": "log", "message": "[WARNING] Dynamic rule engine returned empty. Falling back."})
            all_personas = load_personas_from_json()
            active_personas = [p for p in all_personas if p.get('org') == org_filter or org_filter == 'Global'][:2]
        
        append_event(job_id, {
            "type": "log", 
            "message": f"[SUCCESS] Match: Required Panel ({len(active_personas)} reviewers: {', '.join([p.get('name', 'Unknown') for p in active_personas])})",
            "personas": [{"name": p.get("name"), "role": p.get("roles", [""])[0] if p.get("roles") else p.get("persona", "").split("\n")[0], "image": get_moma_browser_url(p), "last_updated": p.get("last_updated")} for p in active_personas]
        })
        
        append_event(job_id, {"type": "step", "index": 2, "title": "Partner Analysis", "progress": 15})
        append_event(job_id, {"type": "log", "message": "[INFO] Running deep research on target partner"})
        append_event(job_id, {"type": "log", "message": f"[INFO] Executing real-time web semantic search for '{deal_desc}'..."})
        
        research_context = ai_engine.run_research_node(deal_desc)
        append_event(job_id, {"type": "log", "message": "[SUCCESS] Live Context Ingested"})

        append_event(job_id, {"type": "step", "index": 3, "title": "Workspace Intel Fetch", "progress": 20})
        append_event(job_id, {"type": "log", "message": "[INFO] Scanning Gmail and Drive for deal history"})
        append_event(job_id, {"type": "log", "message": "[INFO] Pinging Google Workspace API scopes..."})
        
        workspace_context = workspace_client.gather_workspace_context(deal_desc, creds)
        append_event(job_id, {"type": "log", "message": "[SUCCESS] Internal context connected"})
        
        append_event(job_id, {"type": "step", "index": 4, "title": "Approver OKR Fetch", "progress": 25})
        append_event(job_id, {"type": "log", "message": "[INFO] Fetching Moma OKRs and Risk Tolerance"})
        append_event(job_id, {"type": "log", "message": "[SUCCESS] Loaded specific liability thresholds"})
        
        if method == 'template':
            # STEP 5: BC Simulation Loop (Original Deck Review)
            append_event(job_id, {"type": "step", "index": 5, "title": "Executing Directed Board Critiques", "progress": 50})
            append_event(job_id, {"type": "log", "message": f"[INFO] Orchestrating sequential Agent Debate ({len(active_personas)} personas) on original layout"})
            append_event(job_id, {"type": "log", "message": "[INFO] Loading Board Executive prompt matrices..."})
            critiques = run_sequential_debate_personas(active_personas, slides_data, deal_desc, research_context, workspace_context, job_id)
            append_event(job_id, {"type": "log", "message": f"[CRITICAL] Alignment gaps found in Terms ({len(critiques.split('###')) - 1} critiques generated)"})
            
            # STEP 6: Synthesizing Target Deck
            append_event(job_id, {"type": "step", "index": 6, "title": "Synthesizing Target Deck", "progress": 80})
            append_event(job_id, {"type": "log", "message": "[INFO] Generating layout overrides based on Deal Panel feedback"})
            append_event(job_id, {"type": "log", "message": "[INFO] Invoking Structural SJL Schema execution via AI node..."})
            final_replacements = ai_engine.build_deck_content(deal_desc, research_context, workspace_context, slides_data, previous_critiques=critiques, iteration=1)
            final_virtual_deck = slides_engine.apply_replacements_to_virtual_deck(slides_data, final_replacements)
            
            # STEP 7: Final Payload Assembly
            append_event(job_id, {"type": "step", "index": 7, "title": "Final Deck Assembly", "progress": 95})
            append_event(job_id, {"type": "log", "message": "[INFO] Mapping virtual updated deck to Google Slides API parameters"})
            
            requests_payload = []
            for original_slide, final_slide in zip(slides_data, final_virtual_deck):
                for obj_id in original_slide['text_boxes'].keys():
                    final_text = final_slide['text_boxes'][obj_id]
                    if original_slide['text_boxes'][obj_id] != final_text:
                        requests_payload.extend([
                            {
                                'deleteText': {
                                    'objectId': obj_id,
                                    'textRange': {'type': 'ALL'}
                                }
                            },
                            {
                                'insertText': {
                                    'objectId': obj_id,
                                    'insertionIndex': 0,
                                    'text': final_text
                                }
                            }
                        ])
            
            payload = ai_engine.run_premorteum_node(critiques, workspace_context, str([s['text'] for s in slides_data])) 
            

            payload = re.sub(r'```json', '', payload, flags=re.IGNORECASE)
            payload = re.sub(r'```markdown', '', payload, flags=re.IGNORECASE)
            payload = payload.replace('GEMINI_WAR_ROOM_PAYLOAD', '')
            payload = payload.replace('```', '')
            payload = payload.strip()
            
            parsed_slides = []
            try:
                parsed_slides = json.loads(payload)
            except Exception as e:
                logger.error(f"Failed to parse organic slides JSON: {e}")
                
            # Rebuild service client to flush httplib2 dead TCP connections
            service_slides = slides_engine.get_slides_client(creds)
            pres_obj = slides_engine.get_presentation(service_slides, presentation_id)
            
            if isinstance(parsed_slides, list):
                for s in parsed_slides:
                    requests_payload.extend(
                        slides_engine.build_dynamic_slide_requests(
                            slide_json=s,
                            insertion_index=None,
                            theme_config=slides_data[0].get('theme_config') if slides_data else None
                        )
                    )
            
            try:
                slides_engine.batch_update_presentation(service_slides, presentation_id, requests_payload)
                append_event(job_id, {"type": "log", "message": "[SUCCESS] End-to-End Deck V3 generated successfully"})
                url = f"https://docs.google.com/presentation/d/{presentation_id}/edit"
                append_event(job_id, {"type": "done", "success": True, "url": url, "payload": payload})
                job_key = datastore_client.key('SimulationJob', job_id)
                job = datastore_client.get(job_key)
                if job:
                    job['status'] = 'completed'
                    datastore_client.put(job)
            except Exception as e:
                err_msg = str(e)
                if "Internal error encountered" in err_msg:
                    err_msg = f"Slides API 500: Potential Image URL Fetch Failure (IAP Blocking or GCS Asset Missing). Native API encountered fatal HTTP fetch exception."
                logger.info(f"Failed to mutate slide object: {err_msg}")
                append_event(job_id, {"type": "log", "message": f"[CRITICAL] Batch API Error: {err_msg}"})
                append_event(job_id, {"type": "done", "success": False, "error": err_msg, "message": f"Batch API Error: {err_msg}"})
                job_key = datastore_client.key('SimulationJob', job_id)
                job = datastore_client.get(job_key)
                if job:
                    job['status'] = 'failed'
                    datastore_client.put(job)

        else:
            append_event(job_id, {"type": "step", "index": 5, "title": "Executing Directed Board Critiques"})
            append_event(job_id, {"type": "log", "message": f"[INFO] Orchestrating sequential Agent Debate ({len(active_personas)} personas)"})
            
            raw_hostile_critiques = run_sequential_debate_personas(active_personas, slides_data, deal_desc, research_context, workspace_context, job_id)
            append_event(job_id, {"type": "log", "message": f"[CRITICAL] Alignment gaps found in Terms ({len(raw_hostile_critiques.split('###')) - 1} critiques generated)"})

            append_event(job_id, {"type": "step", "index": 6, "title": "Synthesizing Deal Defense Triads"})
            append_event(job_id, {"type": "log", "message": "[INFO] Passing Hostile Critiques to Mission Critical Coach for Synthesis..."})
            
            # This is the vital "Good-to-Great" Deal Defense generation.
            synthesized_triad_critiques = ai_engine.run_synthesis_coach_node(raw_hostile_critiques, deal_desc)
            aggregated_critiques = synthesized_triad_critiques
            
            append_event(job_id, {"type": "log", "message": "[INFO] Generating Mitigations & Caps"})
            directive = ai_engine.format_hardening_directives(slides_data, aggregated_critiques, deal_desc)
            append_event(job_id, {"type": "log", "message": "[SUCCESS] Guardrails Designed"})
            
            append_event(job_id, {"type": "step", "index": 7, "title": "UX Structural Redesign"})
            append_event(job_id, {"type": "log", "message": "[INFO] Utilizing multi-modal models to ingest slide images and generate brand new dynamic SJL layouts"})


            append_event(job_id, {"type": "log", "message": "[INFO] Appending AI Output Slides at index 0"})
            append_event(job_id, {"type": "log", "message": "[INFO] Requesting Executive Summary synthesis from AI Engine..."})
            exec_summary_payload = ai_engine.run_executive_summary_node(aggregated_critiques)
            exec_summary_payload = re.sub(r'```json', '', exec_summary_payload, flags=re.IGNORECASE).replace('```', '').strip()
            try:
                exec_summary_slides = json.loads(exec_summary_payload)
            except Exception as e:
                logger.error(f"Failed to parse executive summary JSON: {e}")
                exec_summary_slides = []
                
            append_event(job_id, {"type": "log", "message": "[INFO] Parsing executive summary and mapping critique geometry..."})
            dynamic_slides_to_prepend = []
            
            if isinstance(exec_summary_slides, list):
                dynamic_slides_to_prepend.extend(exec_summary_slides)
                
            if directive and hasattr(directive, 'new_terms_block'):
                dynamic_slides_to_prepend.append({
                    "elements": [
                        {"type": "text", "content": "Hardening Directives", "position": {"x": 35, "y": 25, "w": 650, "h": 50}, "style": {"size": 28, "bold": True}},
                        {"type": "text", "content": directive.new_terms_block, "position": {"x": 35, "y": 80, "w": 650, "h": 250}, "style": {"size": 14}}
                    ]
                })
                
            for block in aggregated_critiques.split('### '):
                if not block.strip(): continue
                parts = block.strip().split('\n', 1)
                title = parts[0].replace('BOT Critique:', 'BOT Feedback:').strip()
                if "BOT" not in title.upper():
                    title = f"BOT Feedback: {title}"
                body = parts[1] if len(parts) > 1 else ''
                
                image_url = None
                for p in active_personas:
                    if p.get('name') and p['name'] in title:
                        image_url = get_signed_avatar_url(p)
                        break
                        
                elements = [
                    {"type": "text", "content": title, "position": {"x": 35, "y": 25, "w": 650, "h": 50}, "style": {"size": 28, "bold": True}},
                    {"type": "text", "content": body, "position": {"x": 35, "y": 80, "w": 450, "h": 250}, "style": {"size": 12}}
                ]
                
                if image_url:
                     elements.append({
                         "type": "image",
                         "url": image_url,
                         "position": {"x": 510, "y": 80, "w": 180, "h": 180}
                     })
                
                dynamic_slides_to_prepend.append({"elements": elements})

            # Pass the raw dynamic_slides_to_prepend through the UX Redesign Node to polish them
            append_event(job_id, {"type": "log", "message": "[INFO] Executing final SJL Redesign Pass over raw generated payload"})
            append_event(job_id, {"type": "log", "message": "[INFO] Submitting parsed SJL layout payload to Gemini for structural formatting..."})
            polished_sjl_payload = ai_engine.run_ux_redesign_node(dynamic_slides_to_prepend, deal_desc)
            
            # Clean JSON formatting from Gemini
            polished_sjl_payload = re.sub(r'```json', '', polished_sjl_payload, flags=re.IGNORECASE)
            polished_sjl_payload = re.sub(r'```markdown', '', polished_sjl_payload, flags=re.IGNORECASE)
            polished_sjl_payload = polished_sjl_payload.replace('```', '').strip()
            
            final_dynamic_slides = []
            try:
                parsed_sjl = json.loads(polished_sjl_payload)
                if isinstance(parsed_sjl, dict) and 'slides' in parsed_sjl:
                    final_dynamic_slides = parsed_sjl['slides']
                elif isinstance(parsed_sjl, list):
                    final_dynamic_slides = parsed_sjl
                else:
                    final_dynamic_slides = dynamic_slides_to_prepend
                append_event(job_id, {"type": "log", "message": "[SUCCESS] SJL Redesign compiled successfully"})
            except Exception as e:
                logger.error(f"Failed to parse redesigned SJL payload: {e}")
                final_dynamic_slides = dynamic_slides_to_prepend
                append_event(job_id, {"type": "log", "message": "[CRITICAL] SJL Parsing failed. Falling back to unpolished layout."})

            # Keep index strictly ascending 
            requests_payload = []
            for slide_json in reversed(final_dynamic_slides):
                requests_payload.extend(
                    slides_engine.build_dynamic_slide_requests(
                        slide_json=slide_json,
                        insertion_index=0,
                        theme_config=slides_data[0].get('theme_config') if slides_data else None
                    )
                )
                
            append_event(job_id, {"type": "step", "index": 8, "title": "Authoring Cloud Slides Document"})
            try:
                slides_engine.batch_update_presentation(service_slides, presentation_id, requests_payload)
                append_event(job_id, {"type": "log", "message": "[SUCCESS] Slides generated successfully"})
                url = f"https://docs.google.com/presentation/d/{presentation_id}/edit"
                
                try:
                    append_event(job_id, {"type": "step", "index": 9, "title": "Generating Pre-Mortem 'War Room' Interactive State"})
                    append_event(job_id, {"type": "log", "message": "[INFO] Generating Pre-Mortem insights for the War Room Gem..."})
                    chat_payload = ai_engine.run_premorteum_node(aggregated_critiques, workspace_context, str([s.get('text', '') for s in slides_data]))
                    chat_payload = re.sub(r'```json', '', chat_payload, flags=re.IGNORECASE)
                    chat_payload = re.sub(r'```markdown', '', chat_payload, flags=re.IGNORECASE)
                    chat_payload = chat_payload.replace('GEMINI_WAR_ROOM_PAYLOAD', '')
                    chat_payload = chat_payload.replace('```', '').strip()
                except Exception as e:
                    logger.error(f"Failed to generate Pre-Mortem for War Room: {e}")
                    chat_payload = aggregated_critiques
                    
                append_event(job_id, {"type": "done", "success": True, "url": url, "payload": chat_payload})
                job_key = datastore_client.key('SimulationJob', job_id)
                job = datastore_client.get(job_key)
                if job:
                    job['status'] = 'completed'
                    datastore_client.put(job)
            except Exception as e:
                err_msg = str(e)
                if "Internal error encountered" in err_msg:
                    err_msg = f"Slides API 500: Potential Image URL Fetch Failure (IAP Blocking or GCS Asset Missing). Native API encountered fatal HTTP fetch exception."
                logger.info(f"Failed to mutate slide object: {err_msg}")
                append_event(job_id, {"type": "log", "message": f"[CRITICAL] Batch API Error: {err_msg}"})
                append_event(job_id, {"type": "done", "success": False, "error": err_msg, "message": f"Batch API Error: {err_msg}"})
                job_key = datastore_client.key('SimulationJob', job_id)
                job = datastore_client.get(job_key)
                if job:
                    job['status'] = 'failed'
                    datastore_client.put(job)
        
    except Exception as e:
        traceback.print_exc()
        append_event(job_id, {"type": "done", "success": False, "error": str(e), "message": f"[CRITICAL] Fatal execution error: {e}"})
        job_key = datastore_client.key('SimulationJob', job_id)
        job = datastore_client.get(job_key)
        if job:
            job['status'] = 'failed'
            datastore_client.put(job)
